name: Publish Build Artifacts

on:
  create:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    container: gradle:7.2.0-jdk17
    steps:
      - name: Get Tag
        id: data
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - uses: actions/checkout@v2
      - name: Run Jar Build
        run: gradle bootJar
      - uses: papeloto/action-zip@v1
        with:
          files: build/
          dest: baby-project-server-${{ steps.data.outputs.SOURCE_TAG }}.zip
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          name: "baby-project-server-release-${{ steps.data.outputs.SOURCE_TAG }}"
          files: baby-project-server-${{ steps.data.outputs.SOURCE_TAG }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
